-- ============================================================================
-- 001: Star schema — DRAFT v0 (Gate 1 discovery-dən sonra yekunlaşır).
-- Qreyn qərarları docs/plan.md "Boşluq siyahısı" bölməsinə uyğundur.
-- Konvensiya: source_ref = 1C _IDRRef-in 32 simvollu hex təsviri;
--             boş ref (16 sıfır bayt) → HƏR dim-də key=0 "Naməlum" üzvü
--             (seed insert-lər aşağıda; ETL boş ref-i key=0-a map edir).
-- Partisiyalar: burada yalnız NÜMUNƏ aylar var — backfill partisiyalarını ETL
--             avtomatik yaradır (etl/src/lib/pg.ts ensureMonthPartition);
--             tək partisiya "scope = bir ay" demək DEYİL.
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS raw;    -- staging: MSSQL-dən 1:1 gələn aralıq cədvəllər
CREATE SCHEMA IF NOT EXISTS dwh;    -- star schema
CREATE SCHEMA IF NOT EXISTS mart;   -- semantik view-lar (NL→SQL və BI yalnız bunu görür)
CREATE SCHEMA IF NOT EXISTS etl;    -- run-log, rekonsiliasiya (002-runlog.sql)

-- ------------------------------- DIM-lər -----------------------------------

CREATE TABLE dwh.dim_date (
  date_key        date PRIMARY KEY,
  year            int  NOT NULL,
  quarter         int  NOT NULL,
  month           int  NOT NULL,
  day             int  NOT NULL,
  ym              char(7) NOT NULL,           -- '2026-06'
  weekday         int  NOT NULL,              -- 1=B.e ... 7=Bazar
  is_working_day  boolean NOT NULL DEFAULT true,  -- AZ təqvimi ilə doldurulur
  holiday_name    text
);

CREATE TABLE dwh.dim_org (                    -- hüquqi şəxslər (multi-org!)
  org_key         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_ref      char(32) UNIQUE NOT NULL,
  name            text NOT NULL,
  is_intercompany_counterparty boolean NOT NULL DEFAULT false
);

CREATE TABLE dwh.dim_warehouse (
  warehouse_key   bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_ref      char(32) UNIQUE NOT NULL,
  name            text NOT NULL,
  is_virtual      boolean NOT NULL DEFAULT false
);

CREATE TABLE dwh.dim_customer (               -- apteklər (~1500)
  customer_key    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_ref      char(32) UNIQUE NOT NULL,
  code            text,
  name            text NOT NULL,
  region          text,
  price_type      text,
  is_own_org      boolean NOT NULL DEFAULT false,  -- intercompany filtri üçün
  is_active       boolean NOT NULL DEFAULT true
);

CREATE TABLE dwh.dim_supplier (               -- tədarükçülər (~600)
  supplier_key    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_ref      char(32) UNIQUE NOT NULL,
  code            text,
  name            text NOT NULL,
  country         text,
  is_active       boolean NOT NULL DEFAULT true
);

CREATE TABLE dwh.dim_product (                -- SKU (~15 000)
  product_key     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_ref      char(32) UNIQUE NOT NULL,
  sku             text,
  name            text NOT NULL,
  category        text,
  manufacturer    text,
  unit            text,
  vat_rate        numeric(5,2),
  is_marked       boolean NOT NULL DEFAULT false,  -- DataMatrix izləmə
  is_active       boolean NOT NULL DEFAULT true
);

CREATE TABLE dwh.dim_series (                 -- partiya/seriya + yararlılıq müddəti
  series_key      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 0 = "seriyasız" sətri əl ilə yazılır
  source_ref      char(32) UNIQUE NOT NULL,
  product_key     bigint REFERENCES dwh.dim_product(product_key),
  batch_no        text,
  expiry_date     date                         -- expiry hesabatlarının açarı
);
CREATE INDEX idx_dim_series_expiry ON dwh.dim_series(expiry_date);
-- "Seriyasız" üzv: fact_stock_eod.series_key=0 bu sətrə istinad edir
INSERT INTO dwh.dim_series (series_key, source_ref, batch_no)
VALUES (0, '00000000000000000000000000000000', NULL);

-- ---------------- key=0 "Naməlum" üzvləri (BÜTÜN dim-lər üçün) ----------------
-- 1C-də boş ref = 16 sıfır bayt → ETL bunu key=0-a map edir. 0-üzvlər olmasa
-- inner JOIN-lı mart view-ları naməlum-ref sətirləri SƏSSİZ itirər və
-- rekonsiliasiya ("manatı-manata") pozular. (Architect review 2026-06-11)
-- [Phase 2 ÖHDƏLİYİ] Bu qarant yalnız DDL ilə bağlanmır: transform boş/unmapped
-- ref-i MÜTLƏQ key=0-a map etməlidir — etl/src/lib/refs.ts dimKeyOrUnknown().
-- Qeyd: explicit key YALNIZ bu 0-sentinellər üçündür; real sətirlər həmişə
-- generated key alır (BY DEFAULT-da explicit insert sequence ilə toqquşa bilər).
INSERT INTO dwh.dim_org (org_key, source_ref, name)
VALUES (0, '00000000000000000000000000000000', 'Naməlum');
INSERT INTO dwh.dim_warehouse (warehouse_key, source_ref, name)
VALUES (0, '00000000000000000000000000000000', 'Naməlum');
INSERT INTO dwh.dim_customer (customer_key, source_ref, name)
VALUES (0, '00000000000000000000000000000000', 'Naməlum');
INSERT INTO dwh.dim_supplier (supplier_key, source_ref, name)
VALUES (0, '00000000000000000000000000000000', 'Naməlum');
INSERT INTO dwh.dim_product (product_key, source_ref, name)
VALUES (0, '00000000000000000000000000000000', 'Naməlum');

-- ------------------------------- FAKT-lar ----------------------------------
-- Qaytarmalar: doc_type = -1, məbləğ/miqdar MÜSBƏT saxlanılır →
-- net = SUM(x * doc_type). (plan: "Boşluq siyahısı" №2)

CREATE TABLE dwh.fact_sales_line (
  date_key        date   NOT NULL,
  org_key         bigint NOT NULL,
  warehouse_key   bigint NOT NULL,
  customer_key    bigint NOT NULL,
  product_key     bigint NOT NULL,
  series_key      bigint,                      -- seriya uçotu olmayan mallar üçün NULL
  doc_type        smallint NOT NULL,           -- 1 = satış, -1 = qaytarma
  doc_ref         char(32) NOT NULL,           -- 1C sənəd _IDRRef hex
  doc_no          text,
  line_no         int    NOT NULL,
  qty             numeric(18,3) NOT NULL,
  revenue_gross   numeric(18,4) NOT NULL,      -- ƏDV DAXİL (metrik memo §1)
  vat_amount      numeric(18,4) NOT NULL DEFAULT 0,
  cost_avg        numeric(18,4),               -- orta maya (statusla birgə oxunmalı)
  cost_status     smallint NOT NULL DEFAULT 0, -- 0 = ilkin, 1 = yekun (ay bağlanıb)
  return_of_doc_ref char(32),                  -- qaytarmanın bağlandığı satış (varsa)
  PRIMARY KEY (date_key, doc_ref, line_no)
) PARTITION BY RANGE (date_key);

-- Nümunə partisiyalar (ETL avtomatik yaradır — etl/src/lib/pg.ts ensureMonthPartition)
CREATE TABLE dwh.fact_sales_line_2026_05 PARTITION OF dwh.fact_sales_line
  FOR VALUES FROM ('2026-05-01') TO ('2026-06-01');
CREATE TABLE dwh.fact_sales_line_2026_06 PARTITION OF dwh.fact_sales_line
  FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');

CREATE INDEX idx_fsl_product  ON dwh.fact_sales_line (product_key,  date_key);
CREATE INDEX idx_fsl_customer ON dwh.fact_sales_line (customer_key, date_key);

CREATE TABLE dwh.fact_purchase_line (
  date_key        date   NOT NULL,
  org_key         bigint NOT NULL,
  warehouse_key   bigint NOT NULL,
  supplier_key    bigint NOT NULL,
  product_key     bigint NOT NULL,
  series_key      bigint,
  doc_ref         char(32) NOT NULL,
  line_no         int    NOT NULL,
  qty             numeric(18,3) NOT NULL,
  cost_gross      numeric(18,4) NOT NULL,      -- alış dəyəri (ƏDV daxil/xaric — Gate 1)
  vat_amount      numeric(18,4) NOT NULL DEFAULT 0,
  landed_cost     numeric(18,4) NOT NULL DEFAULT 0, -- доп. расходы payı (M2)
  PRIMARY KEY (date_key, doc_ref, line_no)
) PARTITION BY RANGE (date_key);

CREATE TABLE dwh.fact_purchase_line_2026_06 PARTITION OF dwh.fact_purchase_line
  FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');

CREATE TABLE dwh.fact_stock_eod (              -- gün sonu qalıqlar (hərəkətlərdən materialize)
  date_key        date   NOT NULL,
  warehouse_key   bigint NOT NULL,
  product_key     bigint NOT NULL,
  series_key      bigint NOT NULL DEFAULT 0,   -- 0 = "seriyasız" üzv (PK ifadə qəbul etmir)
  qty             numeric(18,3) NOT NULL,
  value_avg       numeric(18,4),               -- orta maya ilə qiymətləndirmə
  PRIMARY KEY (date_key, warehouse_key, product_key, series_key)
) PARTITION BY RANGE (date_key);

CREATE TABLE dwh.fact_stock_eod_2026_06 PARTITION OF dwh.fact_stock_eod
  FOR VALUES FROM ('2026-06-01') TO ('2026-07-01');

CREATE TABLE dwh.fact_expense (
  date_key        date   NOT NULL,
  org_key         bigint NOT NULL,
  doc_ref         char(32) NOT NULL,
  line_no         int    NOT NULL DEFAULT 0,
  expense_type    text,                        -- xərc maddəsi (Gate 1: sənəd növləri)
  department      text,                        -- ayırma açarı M6 qərarından asılı
  amount          numeric(18,4) NOT NULL,
  PRIMARY KEY (date_key, doc_ref, line_no)
);

-- ------------------------- MART (semantik qat) ------------------------------
-- NL→SQL və Metabase YALNIZ mart.* görür. View-lar Gate 1-dən sonra real
-- sütunlarla yekunlaşır; aşağıdakı imzalar müqavilə xarakterlidir.

CREATE OR REPLACE VIEW mart.v_sales_daily AS
SELECT
  f.date_key                                       AS satis_tarixi,
  o.name                                           AS teskilat,
  c.name                                           AS musteri,
  p.name                                           AS mehsul,
  p.category                                       AS kateqoriya,
  SUM(f.qty * f.doc_type)                          AS miqdar_net,
  SUM(f.revenue_gross * f.doc_type)                AS dovriyye_edv_daxil,
  SUM(f.vat_amount * f.doc_type)                   AS edv,
  SUM((f.revenue_gross - COALESCE(f.cost_avg,0) * f.qty) * f.doc_type) AS marja_ilkin,
  MIN(f.cost_status)                               AS cost_status   -- 0 görünərsə "ilkin"
FROM dwh.fact_sales_line f
JOIN dwh.dim_org      o ON o.org_key      = f.org_key
JOIN dwh.dim_customer c ON c.customer_key = f.customer_key
JOIN dwh.dim_product  p ON p.product_key  = f.product_key
GROUP BY 1,2,3,4,5;

CREATE OR REPLACE VIEW mart.v_stock_expiry AS
SELECT
  s.date_key                                       AS tarix,
  w.name                                           AS anbar,
  p.name                                           AS mehsul,
  se.batch_no                                      AS partiya,
  se.expiry_date                                   AS son_istifade,
  (se.expiry_date - s.date_key)                    AS qalan_gun,
  CASE
    WHEN se.expiry_date IS NULL                    THEN 'seriyasiz'
    WHEN se.expiry_date - s.date_key < 90          THEN 'qirmizi (<3 ay)'
    WHEN se.expiry_date - s.date_key < 180         THEN 'sari (3-6 ay)'
    ELSE 'yasil (>6 ay)'
  END                                              AS expiry_zona,   -- M8 təklifi
  s.qty,
  s.value_avg
FROM dwh.fact_stock_eod s
JOIN dwh.dim_warehouse w  ON w.warehouse_key = s.warehouse_key
JOIN dwh.dim_product   p  ON p.product_key   = s.product_key
LEFT JOIN dwh.dim_series se ON se.series_key = s.series_key;
